version: 0.1
tools:
  definitions:
    - name: markdownlint
      extra_packages: [markdownlint-rule-search-replace]
lint:
  definitions:
    - name: markdownlint
      commands:
        - name: lint
          run: markdownlint ${target} --json -r markdownlint-rule-search-replace
    - name: codespell
      direct_configs:
        - .codespellrc
        - todo_dict.txt
    - name: vale
      direct_configs:
        - .vale.ini
        - styles/base/todo.yml
    - name: semgrep
      commands:
        - name: check
          # Add our custom rules
          run:
            semgrep --config=auto --config=.semgrep.yaml --sarif --output=${tmpfile}
            --include=${target}
    - name: todo-grep-wrapped
      description: Uses grep to look for TODOs
      files: [ALL]
      commands:
        - name: lint
          run: bash ${cwd}/todo_grep.sh ${target}
          output: regex
          parse_regex: "((?P<path>.*):(?P<line>-?\\d+):(?P<col>-?\\d+): \\[(?P<severity>.*)\\] (?P<message>.*) \\((?P<code>.*)\\))"
          success_codes: [0, 1]
    - name: todo-grep-linter
      description: Uses grep to look for TODOs
      files: [ALL]
      commands:
        - name: lint
          run: bash -c "grep -o -E 'TODO[\W]' --line-number --with-filename ${target}"
          success_codes: [0, 1]
          parser:
            run: 'sed -E "s/([^:]*):([0-9]+):(.*)/\1:\2:0: [error] Found \3 in line (TODO)/"'
          output: regex
          parse_regex: "((?P<path>.*):(?P<line>-?\\d+):(?P<col>-?\\d+): \\[(?P<severity>.*)\\] (?P<message>.*) \\((?P<code>.*)\\))"
  exported_configs:
    - configs:
        - cspell.yaml
        - .codespellrc
        - todo_dict.txt
        - .vale.ini
        - styles/base/todo.yml
        - .semgrep.yaml
